//
//  DataDummies.swift
//  Travel ID
//
//  Created by Patricia Fiona on 01/08/21.
//

import Foundation
import UIKit
 
var reviews: [Review] = [
    Review(placeID: 1,
           photo: UIImage(named: "user_01")!,
           title: "Realy Love the View!",
           username: "Jacob Seed",
           description: "Sangat ingin pergi ke sana karena suasana yang nyaman dan indah..."),
    Review(placeID: 1,
           photo: UIImage(named: "user_03")!,
           title: "Tunggu waktu nih...",
           username: "Vincent Yoseph",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 2,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 2,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 3,
           photo: UIImage(named: "user_05")!,
           title: "Dingin yang Terbayarkan...",
           username: "Catalina Ferguson",
           description: "Susasana dingin dikalahkan dengan pemandangan yang super bagus..."),
    Review(placeID: 4,
           photo: UIImage(named: "user_06")!,
           title: "Tunggu waktu nih...",
           username: "Thomas Gautama",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 5,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 5,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
    Review(placeID: 7,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 8,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 9,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 10,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
]
