//
//  DataDummies.swift
//  Travel ID
//
//  Created by Patricia Fiona on 01/08/21.
//

import Foundation
import UIKit

var galeries: [Galery] = [
    Galery(placeID: 1,
           placeImage: "https://asset.kompas.com/crops/7BAA_ly7b-MmcoKLamKOPBypZx8=/53x0:676x415/750x500/data/photo/2020/05/18/5ec278e912802.jpg"),
    Galery(placeID: 1,
           placeImage: "https://akcdn.detik.net.id/visual/2018/10/16/56ec3a2c-9983-4d6d-aae8-2914ac7d055b_169.jpeg?w=650"),
    Galery(placeID: 1,
           placeImage: "https://cdn-2.tstatic.net/travel/foto/bank/images/danau-kelimutu-nusa-tenggara-timur_20180125_185012.jpg"),
    Galery(placeID: 1,
           placeImage: "https://akcdn.detik.net.id/visual/2016/04/01/2507c9e7-72c9-406e-aa74-054c081674c1_169.jpg?w=650"),
    Galery(placeID: 2,
           placeImage: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Indonesia_-_Lake_Toba_%2826224127503%29.jpg"),
    Galery(placeID: 2,
           placeImage: "https://maritim.go.id/konten/unggahan/2016/01/tongging-ok.jpg"),
    Galery(placeID: 2,
           placeImage: "https://koran-jakarta.com/images/article/phpbzvgmg_resized.jpg"),
    Galery(placeID: 2,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2020/09/13/danau-toba_169.jpeg?w=780&q=80"),
    Galery(placeID: 3,
           placeImage: "https://asset.kompas.com/crops/oUbd-oWgmK9GQitYBij1i8DX-1Y=/0x73:1280x713/750x500/data/photo/2019/07/24/5d37bf7ba9d0f.jpg"),
    Galery(placeID: 3,
           placeImage: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Mount_Bromo_at_sunrise%2C_showing_its_volcanoes_and_Mount_Semeru_%28background%29.jpg/1200px-Mount_Bromo_at_sunrise%2C_showing_its_volcanoes_and_Mount_Semeru_%28background%29.jpg"),
    Galery(placeID: 3,
           placeImage: "https://blue.kumparan.com/image/upload/fl_progressive,fl_lossy,c_fill,q_auto:best,w_640/v1598343691/pe2jv1eqlxxtrfusftm2.jpg"),
    Galery(placeID: 3,
           placeImage: "https://asset.kompas.com/crops/jNJCw78jRpATerjMmadbBwqblkE=/0x0:1800x1200/750x500/data/photo/2021/05/10/6099375e04acb.jpg"),
    Galery(placeID: 3,
           placeImage: "https://awsimages.detik.net.id/community/media/visual/2020/08/16/puncak-seruni-gunung-bromo-2_169.jpeg?w=780&q=90"),
]
 
var reviews: [Review] = [
    Review(placeID: 1,
           photo: UIImage(named: "user_01")!,
           title: "Realy Love the View!",
           username: "Jacob Seed",
           description: "Sangat ingin pergi ke sana karena suasana yang nyaman dan indah..."),
    Review(placeID: 1,
           photo: UIImage(named: "user_03")!,
           title: "Tunggu waktu nih...",
           username: "Vincent Yoseph",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 2,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 2,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 3,
           photo: UIImage(named: "user_05")!,
           title: "Dingin yang Terbayarkan...",
           username: "Catalina Ferguson",
           description: "Susasana dingin dikalahkan dengan pemandangan yang super bagus..."),
    Review(placeID: 4,
           photo: UIImage(named: "user_06")!,
           title: "Tunggu waktu nih...",
           username: "Thomas Gautama",
           description: "Kapan ya bisa ke tempat sebagus ini?"),
    Review(placeID: 5,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 5,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 6,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
    Review(placeID: 7,
           photo: UIImage(named: "user_02")!,
           title: "Bagus banget!!!",
           username: "Drake",
           description: "Indonesia emang surganya tempat wisata. Ayo mari berkunjung...!"),
    Review(placeID: 8,
           photo: UIImage(named: "user_03")!,
           title: "Tenang dan Nyaman",
           username: "Vincent Yoseph",
           description: "Tenang dan nyaman suasana alamnya juga oke banget! Recomended!!!"),
    Review(placeID: 9,
           photo: UIImage(named: "user_04")!,
           title: "Tunggu akhir tahun ah...",
           username: "Avandy Jaya",
           description: "Kumpulin uang buat mampir ke sini ah... Pasti bagus banget deh."),
    Review(placeID: 10,
           photo: UIImage(named: "user_04")!,
           title: "Recomended Katanya...",
           username: "Avandy Jaya",
           description: "Kata temen kantor yang uda pernah kesana sih bagus banget katanya. Pokoknya seru deh..."),
]
